#!/bin/bash
clear
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	anggun
# //	Dscription: Xray Menu Management
# //	email: arismar.amar@gmail.com
# //====================================================
# // font color configuration | anggun  aio
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
   clear
   echo -e "\033[1;93m╒═══════════════════════════════════╕\033[0m"
   echo -e "\e[42m       Add Xray/Trojan Account   \E[0m"
   echo -e "\033[1;93m╘═══════════════════════════════════╛\033[0m"

  read -rp "User: " -e user
  user_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${user_EXISTS} == '1' ]]; then
    clear
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\e[42m        Add Xray/Trojan Account          \E[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
    echo "A client with the specified name was already created, please choose another name."
    echo ""
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
  fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
read -p "Limit User (GB): " Quota
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/html/trojan-$user.txt <<-END
_______________________________________________________
           Thank You For Using Our Services
                Xray/Trojan Account
_______________________________________________________
              Format Trojan GO/WS (CDN)
_______________________________________________________

- name: Trojan-$user-GO/WS (CDN)
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}
_______________________________________________________
                 Format Trojan gRPC
_______________________________________________________

- name: Trojan-$user-gRPC (SNI)
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

_______________________________________________________
              Link Trojan Account
_______________________________________________________
Link WS : trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}
_______________________________________________________
Link GRPC : trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}
_______________________________________________________



END
systemctl restart xray
systemctl restart nginx
service cron restart
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid}" >>/etc/trojan/.trojan.db
clear
echo -e "
\033[1;93m╒═══════════════════════════════════╕\033[0m
\e[42mThank You For Using Our Services\E[0m
\e[42mXray/Trojan Account             \E[0m
\033[1;93m╘═══════════════════════════════════╛\033[0m
Remarks    : ${user}
Host       : ${domain}
Location   : $CITY
User Quota : ${Quota} GB
Port TLS   : 443
port       : 443
Key        : ${uuid}
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Link WS    : ${trojanlink}
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Link GRPC  : ${trojanlink1}
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Format OpenClash : http://${domain}:81/trojan-$user.txt
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Expired On : $exp
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
" | tee -a /etc/log-create-user.log
read -n 1 -s -r -p "Press any key to back on menu"

menu
