#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
echo -e "\033[1;93m╒═══════════════════════════════════╕\033[0m"
echo -e "\e[42m      Account ANGGUN  SSH Ovpn          \E[0m"
echo -e "\033[1;93m╘═══════════════════════════════════╛\033[0m"
read -p "Username : " LOGIN
read -p "Password : " PASSWD
read -p "Expired (hari): " expired
IP=$(curl -sS ifconfig.me)
PUB=$( cat /etc/slowdns/server.pub )
NS=`cat /etc/xray/dns`
domain=`cat /etc/xray/domain`
useradd -e `date -d "$EXPIRED days" +"%Y-%m-%d"` -s /bin/false -M $LOGIN
exp="$(chage -l $LOGIN | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD\n$PASSWD\n"|passwd $LOGIN &> /dev/null
cat > /var/www/html/ssh-$LOGIN.txt <<-END
_______________________________________________________
             Account ANGGUN SSH OVPN  
_______________________________________________________

Username         : $LOGIN
Password         : $PASSWD
Expired          : $exp
__________________________________
IP               : $IP
Host             : $domain
Host Slowdns     : ${NS}
Pub Key          : ${PUB}
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109 ,80
Port Dropbear WS : 443, 109
Port SSH WS      : 80
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
Proxy Squid 1    : 3128
Proxy Squid 2    : 8000
Proxy Squid 3    : 8080
BadVPN UDP       : 7100 s/d 7900
__________________________________
Payload WSS: GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
__________________________________
OpenVPN WS SSL : http://$domain:81/ws-ssl.ovpn
OpenVPN SSL : http://$domain:81/ssl.ovpn
OpenVPN TCP : http://$domain:81/tcp.ovpn
OpenVPN UDP : http://$domain:81/udp.ovpn
__________________________________

END
clear
cat > /var/www/html/configmu.txt <<-END
_______________________________________________________
    CONFIG OPOK INDOSAT   HTTPCUSTOM
                          CEK  DENGAN TEPAT
_______________________________________________________
>>>>>Payload<<<<<<

GET wss://[host] [protocol][crlf]Host: covid19.go.id[crlf]Connection: Upgrade[crlf]Upgrade: websocket[crlf][crlf]

>>>>Remote Proxy<<<<

172.67.70.101:443

>>>>SNI<<<<<

$domain

>>>>>>Host-PortSSH<<<<<<

$domain:443@$LOGIN:$PASSWD

__________________________________

END
clear

cat > /var/www/html/configmuu.txt <<-END
_______________________________________________________
 SETUP CONFIG  OPOK TELKOMSEL  HTTPCUSTOM
                              CEK DENGAN TEPAT
_______________________________________________________
>>>>>Payload<<<<<<

GET /worryfree HTTP/1.1[crlf]host: tsel.me[crlf]Connection: keep-alive[crlf]Upgrade: websocket[crlf][crlf]

>>>>>>Host-PortSSH<<<<<<

$domain:80@$LOGIN:$PASSWD

__________________________________

END
clear
echo -e "
\033[1;93m╒═══════════════════════════════════╕\033[0m
\e[42mThank You For Using Our Services\E[0m
\e[42mSSH OVPN Account             \E[0m
\033[1;93m╘═══════════════════════════════════╛\033[0m
Username         : $LOGIN
Password         : $PASSWD
Expired          : $exp
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
IP               : $IP
Host             : $domain
Host Slowdns     : ${NS}
Pub Key          : ${PUB}
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109 ,80
Port Dropbear WS : 443, 109
Port SSH WS      : 80
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
Proxy Squid 1    : 3128
Proxy Squid 2    : 8000
Proxy Squid 3    : 8080
BadVPN UDP       : 7100 s/d 7900
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Payload NONTLS : GET / HTTP/1.1[crlf]host: $domain[crlf]Connection: keep-alive[crlf]Upgrade: websocket[crlf][crlf]
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
OpenVPN WS SSL   : http://$domain:81/ws-ssl.ovpn
OpenVPN SSL      : http://$domain:81/ssl.ovpn
OpenVPN TCP      : http://$domain:81/tcp.ovpn
OpenVPN UDP      : http://$domain:81/udp.ovpn
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
Link Akunmu: http://$domain:81/ssh-$LOGIN.txt
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0-M
Link Indosat Opok: http://$domain:81/configmu.txt
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0-M
Link Telkomsel Opok: http://$domain:81/configmuu.txt
\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m
"  | tee -a /etc/log-create-user.log

read -n 1 -s -r -p "Press any key to back on menu"
menu
